# Generated by Django 3.2.4 on 2021-06-22 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(upload_to='app1/media/images', verbose_name='Icon')),
                ('start_date', models.DateTimeField(verbose_name='Start date')),
                ('addDate', models.DateTimeField(auto_now_add=True, verbose_name='DA')),
                ('order_num', models.IntegerField(verbose_name='Duration')),
                ('end_date', models.DateTimeField(verbose_name='End date')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.project', verbose_name='Project')),
            ],
        ),
        migrations.CreateModel(
            name='StoryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailedUrl', models.URLField(verbose_name='More detUrl')),
                ('detailedText', models.TextField(verbose_name='More Text')),
                ('content_type', models.CharField(max_length=20, verbose_name='Content type')),
                ('content', models.URLField(verbose_name='URL')),
                ('duration', models.IntegerField(verbose_name='Duration')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('story_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.story')),
            ],
        ),
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStoryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_watched', models.FloatField(default=False, verbose_name='Watched')),
                ('watch_date', models.DateTimeField(verbose_name='Watched')),
                ('story_file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.storyfile')),
                ('subs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.subs')),
            ],
        ),
    ]
