# Generated by Django 3.2.4 on 2021-06-22 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210622_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstoryinfo',
            old_name='story_file',
            new_name='user_story_file',
        ),
    ]
